
const admin = require('firebase-admin');

// --- Configuration ---
// This will be populated by the GitHub Action
const serviceAccount = require('../serviceAccountKey.json');

// --- Initialize Firebase Admin ---
if (!admin.apps.length) {
  admin.initializeApp({
    credential: admin.credential.cert(serviceAccount)
  });
}
const db = admin.firestore();

// --- Main Worker Function ---
async function generateContent() {
    console.log('--- Running Gemini Worker ---');

    // 1. Get data from environment variables (passed by GitHub Action)
    const {
        CONTENT_TYPE, 
        CONTENT_SLUG, 
        ISSUE_TITLE, 
        ISSUE_BODY 
    } = process.env;

    if (!CONTENT_TYPE || !CONTENT_SLUG || !ISSUE_TITLE) {
        console.error('Error: Missing required environment variables.');
        process.exit(1);
    }

    console.log(`Received request to generate:`);
    console.log(`  - Type: ${CONTENT_TYPE}`);
    console.log(`  - Slug: ${CONTENT_SLUG}`);
    console.log(`  - Title: ${ISSUE_TITLE}`);

    // 2. Generate boilerplate content (placeholder for actual Gemini API call)
    // TODO: In the future, call Gemini API with ISSUE_BODY as prompt
    console.log('\nGenerating boilerplate content (Gemini API placeholder)...');
    const boilerplateData = getBoilerplate(CONTENT_TYPE, CONTENT_SLUG, ISSUE_TITLE, ISSUE_BODY);

    // 3. Save the generated content to the appropriate 'draft' collection
    const draftCollectionName = `draft-${CONTENT_TYPE === 'post' ? 'post_en' : CONTENT_TYPE}`;
    const docRef = db.collection(draftCollectionName).doc(CONTENT_SLUG);

    console.log(`Saving to Firestore path: ${docRef.path}`);
    try {
        await docRef.set(boilerplateData);
        console.log('Successfully saved to draft collection in Firestore.');
    } catch (error) {
        console.error('Error saving to Firestore:', error);
        process.exit(1);
    }

    // 4. Output the preview URL for the GitHub Action to use
    // This special syntax allows the GitHub Action to pick up the output.
    const previewUrl = `https://ctrlcat.dev/preview.html?type=${CONTENT_TYPE}&slug=${CONTENT_SLUG}`;
    console.log(`\nPreview URL: ${previewUrl}`);
    console.log(`::set-output name=preview_url::${previewUrl}`);
}

function getBoilerplate(type, slug, title, body) {
    const data = {
        type: type === 'post' ? 'blog' : type,
        slug: slug,
        name: { en: `AutoGen Content #${slug}`, ko: `자동 생성 콘텐츠 #${slug}` },
        description: { en: body.substring(0, 100), ko: body.substring(0, 100) },
        desc: { en: `Content generated from issue body:\n\n${body}`, ko: `이슈 내용으로부터 생성된 콘텐츠:\n\n${body}` },
        icon: 'fa-solid fa-robot',
        tags: ['autogen']
    };

    if (type === 'tool') {
        data.script = 'script.js';
        data.scriptContent = `// Autogenerated script for ${slug}\nexport function init() {\n  console.log('Init ${slug}');\n}`;
        data.content = { en: { title: `AutoGen Tool #${slug}` }, ko: { title: `자동 생성 도구 #${slug}` } };
    } else if (type === 'game') {
        data.script = 'script.js';
        data.style = 'style.css';
        data.scriptContent = `// Autogenerated script for ${slug}\nexport function init() {\n  console.log('Init ${slug}');\n}`;
        data.styleContent = `/* Autogenerated style for ${slug} */`;
        data.content = { en: { title: `AutoGen Game #${slug}` }, ko: { title: `자동 생성 게임 #${slug}` } };
    } else if (type === 'post') {
        data.title = `AutoGen Post #${slug}`;
        data.date = new Date().toISOString().split('T')[0];
        data.summary = { en: body.substring(0, 100), ko: body.substring(0, 100) };
        data.contentBody = body;
    }

    return data;
}

// --- Run the worker ---
generateContent();
